# Generated by Django 4.1.2 on 2023-03-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phylogene_app', '0007_alter_userfilesform_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilesform',
            name='file',
            field=models.FileField(upload_to='upload/', verbose_name='Load .csv file'),
        ),
    ]
